### ISSUE TITLE
Boolean conversion gives "InvalidCastException: Object must implement IConvertible" error.

### ISSUE THREAD

**Issue by alexhaloETH** [dojoengine/dojo.unity#19]
When a field in a struct on dojo has a bool type, the unity SDK tries to translate it to a System.Boolean, but the error 
`InvalidCastException: Object must implement IConvertible.`
gets thrown.

![image](https://github.com/dojoengine/dojo.unity/assets/108292891/14ea48a6-3b87-4271-aeb5-6846ae1dc7f5)

How to replicate:

Add a bool type to any struct on the dojo side, example.

`struct PlayerInfo {
    #[key]
    game_id: u32,
    #[key]
    owner: ContractAddress,
    score: u32,
    score_claim_status: bool,
    earned_prize: u128,
    revenant_count: u32,
    outpost_count: u32,
    reinforcement_count: u32,
    initiated: u8,
    inited: bool,
    player_wallet_amount: u128
}`

and try to run the dojo SDK with an entity of that type being present in the dojo world

**Comment by alexhaloETH** [comment]
for now i am using this workaround

`           
else if (field.FieldType == typeof(Boolean))
      {
          field.SetValue(instance, bottlenoselabs.C2CS.Runtime.CBool.ToBoolean((bottlenoselabs.C2CS.Runtime.CBool)value)); 
      }
`

**Comment by Larkooo** [comment]
Hey, nice catch! This should should be fixed with my latest PR.
