### ISSUE TITLE
Burner Storage 

### ISSUE THREAD

**Issue by alexhaloETH** [dojoengine/dojo.unity#35]
Currently, Burners are saved in a list in the burner manager, which means that as soon as the instance of the game is closed the burner data will be lost. To get around this other Web based projects that use a burner Manager  and store the key and address in the local data portion of the web browser, this could give games which last for multiple session a better chance to work.

As for the unity editor, Player Prefs can be used to store the current burner between editor run time sessions

**Comment by Xaxxoo** [comment]
Does this simply mean a normal web2 backend for storing data for a while?
