### ISSUE TITLE
Error on Calls on Webgl

### ISSUE THREAD

**Issue by alexhaloETH** [dojoengine/dojo.unity#62]
Currently trying to call the balance Of function of a ERC20 contract

This is the code I have 

  var addressERC20 = "0x072599086bffce6593a2e08169c21d23564f08be1e1d0b8e05a9768f20469a3f";
        //var owenr = DojoEntitiesDataManager.currentAccount.Address.Hex();
        var owenr = "0x0566295fc2c33edf6c4eb2e5c5fe0b58a062584ced06968e602eba0c0d3dc15f";

        Debug.Log($"addressERC20: {addressERC20}");

        var blockData = new dojo.BlockId()
        {
            tag = dojo.BlockId_Tag.BlockTag_,
            block_tag = dojo.BlockTag.Latest
        };
        Debug.Log($"blockData: tag={blockData.tag}, block_tag={blockData.block_tag}");

        var endpoint = new DojoContractCommunication.EndpointDojoCallStruct(
            addressOfSystem: addressERC20,
            functionName: "balance_of");
        Debug.Log($"endpoint: addressOfSystem={endpoint.addressOfSystem}, functionName={endpoint.functionName}");

        var structBalanceOf = new ERC20ActionsContract.BalanceOfViewStruct(
          endpoint,
          new FieldElement(owenr));

        //Debug.Log($" address={DojoEntitiesDataManager.currentAccount.Address}");

        var balance = await structBalanceOf.BalanceOfCall(DojoEntitiesDataManager.dojoEntInitializer.provider, blockData);
        Debug.Log($"balance: {balance}");

        var actualBalance = RisingRevenantUtils.BigIntToDecimal(RisingRevenantUtils.HexToBigInteger(balance[0].Hex()), 2);
        Debug.Log($"actualBalance: {actualBalance}");

        walletAmount.text = actualBalance.ToString();
        Debug.Log($"walletAmount.text: {walletAmount.text}");
        
         public async Task<FieldElement[]> BalanceOfCall(JsonRpcClient jsonRpcClient, dojo.BlockId blockData)
        {
            var callData = new List<dojo.FieldElement>();

            var endpoint = GetFieldsFromStruct(this, out var fields);

            foreach (var field in fields)
            {
                var fieldValue = field.GetValue(this);

                Debug.Log("in the balance of call " + fieldValue);
                ProcessStructValues(fieldValue, callData);
            }

            Debug.Log("Balance of call data");
            foreach (var VARIABLE in callData)
            {
                Debug.Log(VARIABLE);
            }

            Debug.Log($"function name: {endpointData.functionName} , address systsme {endpointData.addressOfSystem}  ,   length of 
            the array   {callData.Count}  ,  owner   {Owner.Hex()}");

            var call = new dojo.Call
            {
                calldata = callData.ToArray(),
                selector = endpoint.functionName,
                to = new FieldElement(endpoint.addressOfSystem).Inner
            };

            return await jsonRpcClient.Call(call, blockData);
        }
        

This function here works fine when in the editor
![image](https://github.com/user-attachments/assets/81472b30-846f-4a54-871c-2112252b476d)

But when the function is run a WebGL instance it returns this 

![Screenshot 2024-07-24 124658](https://github.com/user-attachments/assets/5e46b1d1-e680-414c-9eed-01984785857d)

by the looks of things some issue on the JS end.

PS: the function in the latest push "Call return Felt" has a mistake in the JsonRpcClient script in the function Call
the webgl part is missing the return 
        
```
      #if UNITY_WEBGL && !UNITY_EDITOR
      await StarknetInterop.CallAsync(client, call, blockId);
```

**Comment by Larkooo** [comment]
Should have been addressed by #60
