### ISSUE TITLE
Provide custom query entities

### ISSUE THREAD

**Issue by mcjkn007** [dojoengine/dojo.unity#63]
For example, when generating entities in WorldManager, custom entities are generated based on config, rather than all of them

**Comment by mcjkn007** [comment]
> Not sure I understand what you mean, could you elaborate?

For example, if a player is playing a farm cultivation game and only needs to know the data of their own farm, rather than all the players' data, can a parameter be added during torii initialization to only retrieve their data?

**Comment by ScottyDavies** [comment]
Hello @mcjkn007 I am open to work on this
