### ISSUE TITLE
Composite Queries with Multiple Clause Crashes editor

### ISSUE THREAD

**Issue by alexhaloETH** [dojoengine/dojo.unity#78]
When i have multiple clauses in one composite query the editor crashes without triggering the unity crash report window.

If i were to have only one clause it works fine.

It runs fine on WbbGL and fetches the necessary entities all fine.

**Comment by Larkooo** [comment]
So works fine on WebGL but crashes on editor?

**Comment by alexhaloETH** [comment]
yh

**Comment by Larkooo** [comment]
should be fixed
